###服务启动端口号
server:
  port: 8010
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: com.zql.order
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://127.0.0.1:8100/eureka/
           #,http://localhost:9100/eureka
###因为该应用为注册中心，
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true